In [4]:
import numpy as np
from scipy.stats import unitary_group
from numpy import linalg as LA
from scipy.linalg import block_diag
from scipy.linalg import logm, expm
import qiskit
#functions
def h(xx):
    x=np.real(xx)
    return -x*np.log2(x)-(1-x)*np.log2(1-x)
def H(v):
    summ=0
    d=len(v)
    for j in range(d):
        summ=summ+h(v[j])
    return summ

In [21]:
#choose w vector
ws=[]
for j in range(100):
    w=np.array([np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand()])
    t=sum(w)
    w=np.sort(w)
    d=len(w)
    haveconjecture=True
    if t/5<(w[1]+w[2])/2:
        vconj=np.array([(w[1]+w[2])/2,(w[1]+w[2])/2,(w[0]+w[3]+w[4])/3,(w[0]+w[3]+w[4])/3,(w[0]+w[3]+w[4])/3,])
        Iconj=H(vconj)
        print("1st regime")
        ws.append(w)
    elif t/5>(w[2]+w[3])/2:
        vconj=np.array([(w[2]+w[3])/2,(w[2]+w[3])/2,(w[0]+w[1]+w[4])/3,(w[0]+w[1]+w[4])/3,(w[0]+w[1]+w[4])/3,])
        Iconj=H(vconj)
        print("2nd regime")
        ws.append(w)
    else:
        haveconjecture=False
        print("unknown regime")

unknown regime
unknown regime
unknown regime
unknown regime
1st regime
unknown regime
unknown regime
unknown regime
1st regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
1st regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
2nd regime
unknown regime
unknown regime
2nd regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
1st regime
unknown regime
2nd regime
1st regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
1st regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
2nd regime
2nd regime
1st regime
unknown regime
2nd regime
2nd regime
unknown regime
unknown regime
unknown regime
2nd regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime
1st regime
unknown regime
unknown regime
unknown regime
unknown regime
unknown regime

In [20]:
ws

[array([0.06107393, 0.09195662, 0.17570817, 0.31671073, 0.79044988]),
 array([0.17141052, 0.1879521 , 0.19878319, 0.25597978, 0.72284858]),
 array([0.11720914, 0.58447904, 0.62896595, 0.67608258, 0.83311845]),
 array([0.05643196, 0.07543735, 0.08430196, 0.18567166, 0.76125603]),
 array([0.48612207, 0.51768943, 0.59436303, 0.61219746, 0.96326387]),
 array([0.01507189, 0.06700813, 0.09221116, 0.35646417, 0.67562343]),
 array([0.05992716, 0.11306935, 0.13708026, 0.27367042, 0.86992894]),
 array([0.03294419, 0.55511419, 0.82555108, 0.88060291, 0.99802625]),
 array([0.10149043, 0.40318086, 0.69534272, 0.69545063, 0.77544863]),
 array([0.10388813, 0.4801112 , 0.62125352, 0.6466061 , 0.85106515]),
 array([0.12499359, 0.394975  , 0.47638738, 0.52556822, 0.65358446]),
 array([0.07702118, 0.11036463, 0.20356913, 0.30515876, 0.67132918]),
 array([0.17428388, 0.37172466, 0.382868  , 0.38380627, 0.86961459]),
 array([0.10923816, 0.14112318, 0.1491044 , 0.22990538, 0.62427163]),
 array([0.22172124, 

In [27]:
b=ws[5]

In [28]:
type(b)

numpy.ndarray

In [32]:
cc=array([1.,2.])

NameError: name 'array' is not defined

In [31]:
type(cc)

numpy.ndarray

In [1]:
7+7

14