In [2]:
import numpy as np
from scipy.stats import unitary_group
from numpy import linalg as LA
from scipy.linalg import block_diag
from scipy.linalg import logm, expm
import qiskit

In [3]:
#functions
def h(x):
    return -x*np.log(x)-(1-x)*np.log(1-x)
def H(v):
    summ=0
    for j in range(5):
        summ=summ+h(v[j])
    return summ

#the following functions Hj refer to the jth regime/jth schur horn procedure

#def H1(w):
#    v=...
#    return H(v)
def H2(w):
    appo=(w[0]+w[3]+w[4])/3
    appo2=(w[1]+w[2])/2
    v=np.array([appo,appo,appo,appo2,appo2])
    return H(v)
def H3(w):
    appo=(w[0]+w[1]+w[4])/3
    appo2=(w[2]+w[3])/2
    v=np.array([appo,appo,appo,appo2,appo2])
    return H(v)
def H4(w):
    appo=(w[0]+w[2]+w[4])/3
    appo2=(w[1]+w[3])/2
    v=np.array([appo,appo,appo,appo2,appo2])
    return H(v)



def Hmax(w):
    return max([H2(w),H3(w),H4(w)])
    

In [4]:
#sampling
#number of w's
n=10
#number of unitaries per w
m=10000

found=0

for j in range(n):
    #random w
    ww=np.array([np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand()])
    w=np.sort(ww)
    gamma0=np.diag(w)
    #v=np.array([0,0,0,0,0])
    t=sum(w)
    Imax=0
    Inew=0
    #sample some unitaries
    for k in range(m):
        U=unitary_group.rvs(5)
        Udag=np.transpose(np.conjugate(U))
        gamma=np.matmul(U,np.matmul(gamma0,Udag))
        #print(gamma.round(2))
        block1=gamma[0:2,0:2]
        block2=gamma[2:4,2:4]
        block1ev=LA.eigvals(block1)
        block2ev=LA.eigvals(block2)
        v=np.array([block1ev[0].real,block1ev[1].real,block2ev[0].real,block2ev[1].real,gamma[4][4].real])
        #v[0]=block1ev[0].real
        #v[1]=block1ev[1].real
        #v[2]=block2ev[0].real
        #v[3]=block2ev[1].real
        #v[4]=gamma[4][4].real
        #print(v)
        Inew=H(v)
        if Inew>Imax:
        #for j in range(4):
        #    vbest[j]=v[j]
            Imax=Inew
    print(w)
    if H2(w)>Imax:
        print("Could be 2nd regime. H2(w) - Imax(w) = ", H2(w)-Imax)
    if H3(w)>Imax:
        print("Could be 3th regime. H3(w) - Imax(w) = ", H3(w)-Imax)
    if H4(w)>Imax:
        print("Could be 4th regime. H4(w) - Imax(w) = ", H4(w)-Imax)
    #if H5(w)>Imax:
    #    print("Could be 5th regime. H5(w) - Imax(w) = ", H5(w)>Imax)
    print("Difference from bound: 5*h(t/5) - Imax(w) = ", 5*h(t/5)-Imax,"\n")
    print("Imax = ", Imax)


[0.00745872 0.40389359 0.54935741 0.89222038 0.93392882]
Difference from bound: 5*h(t/5) - Imax(w) =  0.013493286704004959 

Imax =  3.4192547906436572
[0.40131235 0.49569489 0.74771008 0.79199626 0.9216095 ]
Could be 4th regime. H4(w) - Imax(w) =  0.00168141030503266
Difference from bound: 5*h(t/5) - Imax(w) =  0.0075059965969788145 

Imax =  3.157461541205627
[0.16324498 0.23936929 0.2894876  0.89850136 0.97181316]
Could be 4th regime. H4(w) - Imax(w) =  0.013425827358872766
Difference from bound: 5*h(t/5) - Imax(w) =  0.034733506531760217 

Imax =  3.429443911951802
[0.09317086 0.42803921 0.55498112 0.57500366 0.82764667]
Could be 2nd regime. H2(w) - Imax(w) =  0.007885673684549843
Could be 4th regime. H4(w) - Imax(w) =  0.00778589203537372
Difference from bound: 5*h(t/5) - Imax(w) =  0.008006563702766645 

Imax =  3.4575502642584537
[0.28481053 0.37901707 0.63685042 0.70945544 0.72763775]
Could be 2nd regime. H2(w) - Imax(w) =  0.0002918336238226793
Could be 4th regime. H4(w) - Ima

In [5]:
H4([0.07604938, 0.39527362, 0.68688096, 0.79238033, 0.97215315])

3.393317104908718

In [6]:
t=sum([0.07604938, 0.39527362, 0.68688096, 0.79238033, 0.97215315])
5*h(t/5)

3.3939085161436013

In [55]:
h(0.68688096)+4*h(sum([0.07604938, 0.39527362, 0.79238033, 0.97215315])/4)

3.366283322157992